/* Podcast episode manifest.
 *
 * One entry per episode, grouped by season year. Newest year renders first,
 * and within a year episodes render in the order listed here.
 *
 * Fields:
 *   title       required — episode name shown in the table
 *   description required — one or two sentences; kept short for the table cell
 *   audio       path to the audio file. Files live in assets/podcasts/<year>/,
 *               named ep<NN>-<kebab-title>.mp3.
 *               Omit it and the row renders with the play button disabled.
 *   date        optional ISO date (YYYY-MM-DD) shown under the title
 *   duration    optional human string, e.g. "42:10"
 *   art         square cover image, assets/podcasts/art/<slug>.png. Generated by
 *               scripts/build_podcast_art.py — add the episode there too.
 *               Keep the ?v= token: bump_assets.py rewrites it, and without it
 *               a rebuilt cover stays stale in every visitor's cache.
 *   slug        stable id used for analytics event paths and the play-count
 *               badge. Derived from the audio filename when omitted — but set
 *               it explicitly if you ever rename an audio file, or the episode
 *               starts a new count from zero.
 */
export const PODCAST_EPISODES = {
    2026: [
        {
            title: "Episode 2 — Week One Is In The Books",
            date: "2026-09-16",
            duration: "9:09",
            slug: "2026-02-week-one-is-in-the-books",
            audio: "assets/podcasts/2026/ep02-week-one-is-in-the-books.mp3",
            art: "assets/podcasts/art/2026-02-week-one-is-in-the-books.png?v=202609161008",
            description: "Ghost of New Jeantys hung 166.2 on the league — Jeanty 29.7, Dart 25.6, Bijan 25.3 — while Mickey C's managed 69.92 and the draft grades started lying immediately. Five of six games were blowouts, Cameron Dicker scored two for the team named after him, and only Bower Outage over Salamander stayed inside thirteen points.",
        },
        {
            title: "Episode 1 — The Grades Are In",
            date: "2026-09-03",
            duration: "14:12",
            slug: "2026-01-the-grades-are-in",
            audio: "assets/podcasts/2026/ep01-the-grades-are-in.mp3",
            art: "assets/podcasts/art/2026-01-the-grades-are-in.png?v=202609161008",
            description: "Draft recap and season predictions, graded off the site's own draft panel: three tiers, twelve teams, predicted standings and awards.",
        },
    ],
};
